// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicAddItemOption,
  DefaultAddItemOptionProps
} from "./plasmic/isv/PlasmicAddItemOption";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import { addProductState } from "../lib/state-management";
import { useSnapshot } from "valtio";
import { useDataEnv } from "@plasmicapp/host";


export interface AddItemOptionProps extends DefaultAddItemOptionProps {}

function AddItemOption_(
  props: AddItemOptionProps,
  ref: HTMLElementRefOf<"div">
) {
  const { ...rest } = props;

  const optionId = props.id;
  const productStateSnap = useSnapshot(addProductState)


  return <PlasmicAddItemOption 
    root={{ ref }} 
    {...rest} 
    currentQuantity={`${productStateSnap.sumOfOptionValuesQuantity[optionId] ?? 0}`}
  />;
}

const AddItemOption = React.forwardRef(AddItemOption_);
export default AddItemOption;
