// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { addToCart } from "../lib/cart";
import { fetchContentfulEntries } from "../components/contentful";
import {
  PlasmicHomepage,
  DefaultHomepageProps
} from "./plasmic/isv/PlasmicHomepage";
import { useSnapshot } from "valtio";
import { addProductState, AppPage, state } from "../lib/state-management";
import { Product } from "../lib/common";

export interface HomepageProps extends DefaultHomepageProps {
}

function Homepage(props: HomepageProps) {
  const ref = React.createRef<HTMLDivElement>();
  const { cart } = useSnapshot(state);
  const products = fetchContentfulEntries('eventMenuItem');

  React.useEffect(() => {
    if (cart.lineItems.length > 0) {
      const menuOffset = document.getElementById("menu")?.offsetTop ?? 0;
      window.scrollTo({
        top: menuOffset,
        behavior: "smooth"
      })
    }
  }, [ref]);
  return <PlasmicHomepage
    root={{ ref }}
    menuItem={{
      onSelect: (id) => {
        if (!id) {
          return ;
        }
        addProductState.productId = id;
        const product = products?.items.find((product: any) => product.sys.id === id);
        if ((product?.fields.options ?? []).length === 0) {
          addProductState.product = product;
          addProductState.productId = id;
          addProductState.optionValues = {};
          addToCart();
          state.appPage = AppPage.checkout;
        } else {
          state.appPage = AppPage.addItem;
        }
      }
    }}
    cartButton={{
      isEmpty: cart.lineItems.length === 0,
      quantity: cart.totalQuantity,
      onClick: () => state.appPage = AppPage.checkout
    }}
  />
}

export default Homepage;
