// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicOptionItem,
  DefaultOptionItemProps
} from "./plasmic/isv/PlasmicOptionItem";
import { useSelector } from "@plasmicapp/host";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface OptionItemProps extends Omit<DefaultOptionItemProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultOptionItemProps altogether and have
// total control over the props for your component.
export interface OptionItemProps extends DefaultOptionItemProps {}

function OptionItem_(props: OptionItemProps, ref: HTMLElementRefOf<"div">) {
  const menuItem = useSelector("contentfulItem")

  console.log("dale", menuItem);
  return <PlasmicOptionItem root={{ ref }} {...props} />;
}

const OptionItem = React.forwardRef(OptionItem_);
export default OptionItem;
