// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicShoppingCart,
  DefaultShoppingCartProps
} from "./plasmic/isv/PlasmicShoppingCart";
import { HTMLElementRefOf } from "@plasmicapp/react-web";
import ShoppingCartLineItem from "./ShoppingCartLineItem";
import { getProductVariantPrice, updateCart } from "../lib/cart";
import { formatPrice } from "../lib/common";
import { useSnapshot } from "valtio";
import { AppPage, state } from "../lib/state-management";
import { goToCheckout } from "../lib/checkout";
import { useRouter } from "next/router";

export interface ShoppingCartProps extends DefaultShoppingCartProps {}

function isValidEmail(email: string) {
  return /\S+@\S+\.\S+/.test(email);
}

function ShoppingCart_(props: ShoppingCartProps, ref: HTMLElementRefOf<"div">) {
  throw new Error("aasd");
  return <h1>Ola</h1>
}

const ShoppingCart = React.forwardRef(ShoppingCart_);
export default ShoppingCart;
