// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { formatPrice, getQuantityItem, getTotalPrice, handleQuantityChange, newCart } from "../common";
import OrderItem from "../components/OrderItem";

import { ScreenVariantProvider } from "../components/plasmic/isv/PlasmicGlobalVariant__Screen";
import { PlasmicHomepage } from "../components/plasmic/isv/PlasmicHomepage";

import options from "../data.json";

function Homepage() {
  const [cart, setCart] = React.useState(newCart());

  console.log(cart);
  return <PlasmicHomepage
    options={{
      children: options.map(option =>(
        <OrderItem
          key={option.id}
          title={option.name}
          description={option.description}
          price={`R$ ${formatPrice(option.price)}`}
          quantity={getQuantityItem(option, cart)}
          onChangeQuantity={handleQuantityChange(option, cart, setCart)}
        />
      ))
    }}
    shoppingCart={{lineItems: cart.lineItems, cart, setCart}}
    totalPrice={formatPrice(getTotalPrice(cart))}
  />;
}

export default Homepage;
